# Kubernetes compute node default networking template
#
parameters:
  linux:
    network:
      interface:
        ens2: ${_param:linux_deploy_interface}
        ens3:
          enabled: true
          type: eth
          proto: static
          name: ${_param:primary_first_nic}
          address: ${_param:single_address}
          netmask: ${_param:control_network_netmask}
          post_up_cmds:
            - ip r rep 10.254.0.0/16 via ${_param:single_address}
        ens4:
          enabled: true
          type: eth
          proto: static
          name: ${_param:primary_second_nic}
          address: ${_param:tenant_address}
          netmask: ${_param:tenant_network_netmask}
