classes:
- service.etcd.server.cluster
- system.haproxy.proxy.listen.kubernetes.apiserver
- system.linux.system.repo.docker_legacy
- system.linux.system.repo.mcp.extra
- system.linux.system.repo.mcp.apt_mirantis.ubuntu
- system.linux.system.repo.mcp.apt_mirantis.saltstack_2016_3
- system.salt.minion.cert.etcd_server
- system.kubernetes.master.cluster
- cluster.vlab.kubernetes.compute
- cluster.vlab.infra
#- cluster.vlab.infra.kvm04
parameters:
  _param:
    keepalived_vip_interface: ens3
    keepalived_vip_virtual_router_id: 65
  etcd:
    server:
      source:
        engine: docker_hybrid
      ssl:
        enabled: True
      setup:
        calico:
          key: /calico/v1/ipam/v4/pool/${_param:calico_private_network}-${_param:calico_private_netmask}
          value: '{"masquerade":true,"cidr":"${_param:calico_private_network}/${_param:calico_private_netmask}"}'
          # if IP-in-IP is required
          # value: '{"ipip":"tunl0","ipip_mode":"always","ipam":true,"disabled":false, "masquerade":true,"cidr":"${_param:calico_private_network}/${_param:calico_private_netmask}"}'
  kubernetes:
    master:
      etcd:
        ssl:
          enabled: True
      network:
        etcd:
          ssl:
            enabled: True
        prometheus:
          enabled: true
      namespace:
        netchecker:
          enabled: true
    common:
      addons:
        externaldns:
          enabled: False
          namespace: kube-system
          image: mirantis/external-dns:latest
          domain: ${_param:kubernetes_cluster_domain}
          provider: coredns
        netchecker:
          enabled: true
        helm:
          enabled: false
        dashboard:
          enabled: true
