parameters:
  _param:
    # General
    linux_system_codename: xenial
    salt_minion_ca_host: ${_param:infra_config_hostname}.${_param:cluster_domain}
    salt_minion_ca_authority: salt_master_ca
    primary_first_nic: ens3
    primary_second_nic: ens4

    # kubernetes settings
    kubernetes_admin_user: admin
    kubernetes_admin_password: ${_param:kubernetes_admin_password_generated}
    kubernetes_admin_token: ${_param:kubernetes_admin_token_generated}
    kubernetes_kubelet_token: ${_param:kubernetes_kubelet_token_generated}
    kubernetes_kube-proxy_token: ${_param:kubernetes_kube-proxy_token_generated}
    kubernetes_scheduler_token: ${_param:kubernetes_scheduler_token_generated}
    kubernetes_controller-manager_token: ${_param:kubernetes_controller-manager_token_generated}
    kubernetes_dns_token: ${_param:kubernetes_dns_token_generated}
    etcd_initial_token: ${_param:etcd_initial_token_generated}

    # addresses and hostnames
    kubernetes_internal_api_address: 10.254.0.1
    kubernetes_internal_dns_address: 10.254.0.10
    kubernetes_control_hostname: ctl
    kubernetes_control_address: 192.168.1.130
    kubernetes_control_node01_hostname: k8s-ctl01
    kubernetes_control_node02_hostname: k8s-ctl02
    kubernetes_control_node03_hostname: k8s-ctl03
    kubernetes_control_node01_address: 192.168.1.131
    kubernetes_control_node02_address: 192.168.1.132
    kubernetes_control_node03_address: 192.168.1.133
    kubernetes_proxy_hostname: prx
    kubernetes_proxy_node01_hostname: prx01
    kubernetes_proxy_node02_hostname: prx02
    kubernetes_proxy_address: 172.17.18.5
    kubernetes_proxy_node01_address: 172.17.18.6
    kubernetes_proxy_node02_address: 172.17.18.7
    kubernetes_control_node01_deploy_address: 192.168.0.131
    kubernetes_control_node02_deploy_address: 192.168.0.132
    kubernetes_control_node03_deploy_address: 192.168.0.133
    kubernetes_proxy_node01_deploy_address: 192.168.0.6
    kubernetes_proxy_node02_deploy_address: 192.168.0.7
    kubernetes_compute_rack01_single_subnet: 192.168.1
    kubernetes_compute_rack01_tenant_subnet: 192.168.2
    kubernetes_compute_rack01_hostname: k8s-cmp
    kubernetes_compute_rack01_deploy_subnet: 192.168.0
    kubernetes_compute_node001_deploy_address: ${_param:kubernetes_compute_rack01_deploy_subnet}.141
    kubernetes_compute_node002_deploy_address: ${_param:kubernetes_compute_rack01_deploy_subnet}.142
    kubernetes_compute_node003_deploy_address: ${_param:kubernetes_compute_rack01_deploy_subnet}.143
    kubernetes_compute_node004_deploy_address: ${_param:kubernetes_compute_rack01_deploy_subnet}.144

    # k8s Images

    cluster_vip_address: ${_param:kubernetes_control_address}
    cluster_local_address: ${_param:single_address}
    glusterfs_service_host: ${_param:kubernetes_control_node03_address}
    # etcd stuff
    cluster_node01_hostname: ${_param:kubernetes_control_node01_hostname}
    cluster_node01_address: ${_param:kubernetes_control_node01_address}
    cluster_node01_port: 4001
    cluster_node02_hostname: ${_param:kubernetes_control_node02_hostname}
    cluster_node02_address: ${_param:kubernetes_control_node02_address}
    cluster_node02_port: 4001
    cluster_node03_hostname: ${_param:kubernetes_control_node03_hostname}
    cluster_node03_address: ${_param:kubernetes_control_node03_address}
    cluster_node03_port: 4001

    kubernetes_kubedns_enabled: True
    kubernetes_externaldns_enabled: False
    kubernetes_coredns_enabled: False
    kubernetes_virtlet_enabled: True
    kubernetes_flannel_enabled: False
    kubernetes_genie_enabled: False
    kubernetes_calico_enabled: True
    kubernetes_opencontrail_enabled: False
    kubernetes_metallb_enabled: False
    # calico
    calico_private_network: 10.0.0.0
    calico_private_netmask: 16
    kubernetes_control_node01_tenant_address: 192.168.2.131
    kubernetes_control_node02_tenant_address: 192.168.2.132
    kubernetes_control_node03_tenant_address: 192.168.2.133

  linux:
    network:
      resolv:
        dns:
          - ${_param:dns_server01}
          - ${_param:dns_server02}
          - ${_param:kubernetes_internal_dns_address}
        search:
          - ${_param:cluster_domain}            
      host:
#        prx:
#          address: ${_param:kubernetes_proxy_address}
#          names:
#          - ${_param:kubernetes_proxy_hostname}
#          - ${_param:kubernetes_proxy_hostname}.${_param:cluster_domain}
#        prx01:
#          address: ${_param:kubernetes_proxy_node01_address}
#          names:
#          - ${_param:kubernetes_proxy_node01_hostname}
#          - ${_param:kubernetes_proxy_node01_hostname}.${_param:cluster_domain}
#        prx02:
#          address: ${_param:kubernetes_proxy_node02_address}
#          names:
#          - ${_param:kubernetes_proxy_node02_hostname}
#          - ${_param:kubernetes_proxy_node02_hostname}.${_param:cluster_domain}
        ctl:
          address: ${_param:kubernetes_control_address}
          names:
          - ${_param:kubernetes_control_hostname}
          - ${_param:kubernetes_control_hostname}.${_param:cluster_domain}
        ctl01:
          address: ${_param:kubernetes_control_node01_address}
          names:
          - ${_param:kubernetes_control_node01_hostname}
          - ${_param:kubernetes_control_node01_hostname}.${_param:cluster_domain}
        ctl02:
          address: ${_param:kubernetes_control_node02_address}
          names:
          - ${_param:kubernetes_control_node02_hostname}
          - ${_param:kubernetes_control_node02_hostname}.${_param:cluster_domain}
        ctl03:
          address: ${_param:kubernetes_control_node03_address}
          names:
          - ${_param:kubernetes_control_node03_hostname}
          - ${_param:kubernetes_control_node03_hostname}.${_param:cluster_domain}
