classes:
- system.backupninja.server.single
- system.xtrabackup.server.single
- system.ceph.backup.server.single
- system.glusterfs.client.cluster
- system.glusterfs.client.volume.backup
parameters:
  _param:
    backupninja_public_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDIAa2WVrnCDxiMRu43VYg7JMrvTqNTjCfz/0ycGV4Lyn359o4HgGgwU3mAkg9pS9x1uGMwb6oelsql54LH90VirBIt6bZIgF0beJK+v0UBb4Y1Qf/rid7iTdpeg0gfzcX/0gnVPdpukkBv8zUhKBx9KbzX5azkBMQLgRD7+Q4eLYagsKMpYH5IhtwfLMX/ty6/h3uMZDYyz1wOjUKYv82antJCS8qMzdHMk3mnWsWKsiq8hipN2Eff/5KWAYv2eg352YVYi3h6NHd9Lxyculuw0L8g2ir2oesnLLxgR3GbHDY9Jz9n1fYQK0Wz79tgrd8qRxhWAUXEqXuzPh/b2dNf
    xtrabackup_public_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDIAa2WVrnCDxiMRu43VYg7JMrvTqNTjCfz/0ycGV4Lyn359o4HgGgwU3mAkg9pS9x1uGMwb6oelsql54LH90VirBIt6bZIgF0beJK+v0UBb4Y1Qf/rid7iTdpeg0gfzcX/0gnVPdpukkBv8zUhKBx9KbzX5azkBMQLgRD7+Q4eLYagsKMpYH5IhtwfLMX/ty6/h3uMZDYyz1wOjUKYv82antJCS8qMzdHMk3mnWsWKsiq8hipN2Eff/5KWAYv2eg352YVYi3h6NHd9Lxyculuw0L8g2ir2oesnLLxgR3GbHDY9Jz9n1fYQK0Wz79tgrd8qRxhWAUXEqXuzPh/b2dNf
    ceph_backup_public_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDIAa2WVrnCDxiMRu43VYg7JMrvTqNTjCfz/0ycGV4Lyn359o4HgGgwU3mAkg9pS9x1uGMwb6oelsql54LH90VirBIt6bZIgF0beJK+v0UBb4Y1Qf/rid7iTdpeg0gfzcX/0gnVPdpukkBv8zUhKBx9KbzX5azkBMQLgRD7+Q4eLYagsKMpYH5IhtwfLMX/ty6/h3uMZDYyz1wOjUKYv82antJCS8qMzdHMk3mnWsWKsiq8hipN2Eff/5KWAYv2eg352YVYi3h6NHd9Lxyculuw0L8g2ir2oesnLLxgR3GbHDY9Jz9n1fYQK0Wz79tgrd8qRxhWAUXEqXuzPh/b2dNf
  backupninja:
    server:
      home_dir: /srv/volumes/backup/backupninja
  xtrabackup:
    server:
      backup_dir: /srv/volumes/backup/xtrabackup
  ceph:
    backup:
      backup_dir: /srv/volumes/backup/ceph
