classes:
- system.backupninja.server.single
- system.xtrabackup.server.single
- system.ceph.backup.server.single
- system.glusterfs.client.cluster
- system.glusterfs.client.volume.backup
parameters:
  _param:
    backupninja_public_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCjE8l/jg6hL4SLW1QAlkOIk3KYxro9caQ7sZ5RPhHF2LWccRnNxULT5f2HD6LlrkgoGWOMQ7vd2arouittP7uldsjCCO+sPPUXP55cAC3WR0Lt7ZoQOaBfkXOtLJVR6VswOlQq4airv1eQNvzoflhnLz1Rmvu2MljHJVP+Fj4ft73GufHMz9QfxFb3qXGYdtoNvb0izO+gv1fnui37AtxAPOgd3sx08nPrWkQonbLnbUCLX8AnANLyH2SiM21f7L3cFPbZ9ioClPE5Z7id2fcEfj6U6OfhlYjWpZbnanA8dm2ZdVKFUwjOy13W2O5bZqKYNDNBgkYFHpVRujEfxBU1
    xtrabackup_public_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCjE8l/jg6hL4SLW1QAlkOIk3KYxro9caQ7sZ5RPhHF2LWccRnNxULT5f2HD6LlrkgoGWOMQ7vd2arouittP7uldsjCCO+sPPUXP55cAC3WR0Lt7ZoQOaBfkXOtLJVR6VswOlQq4airv1eQNvzoflhnLz1Rmvu2MljHJVP+Fj4ft73GufHMz9QfxFb3qXGYdtoNvb0izO+gv1fnui37AtxAPOgd3sx08nPrWkQonbLnbUCLX8AnANLyH2SiM21f7L3cFPbZ9ioClPE5Z7id2fcEfj6U6OfhlYjWpZbnanA8dm2ZdVKFUwjOy13W2O5bZqKYNDNBgkYFHpVRujEfxBU1
    ceph_backup_public_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCjE8l/jg6hL4SLW1QAlkOIk3KYxro9caQ7sZ5RPhHF2LWccRnNxULT5f2HD6LlrkgoGWOMQ7vd2arouittP7uldsjCCO+sPPUXP55cAC3WR0Lt7ZoQOaBfkXOtLJVR6VswOlQq4airv1eQNvzoflhnLz1Rmvu2MljHJVP+Fj4ft73GufHMz9QfxFb3qXGYdtoNvb0izO+gv1fnui37AtxAPOgd3sx08nPrWkQonbLnbUCLX8AnANLyH2SiM21f7L3cFPbZ9ioClPE5Z7id2fcEfj6U6OfhlYjWpZbnanA8dm2ZdVKFUwjOy13W2O5bZqKYNDNBgkYFHpVRujEfxBU1
  backupninja:
    server:
      home_dir: /srv/volumes/backup/backupninja
  xtrabackup:
    server:
      backup_dir: /srv/volumes/backup/xtrabackup
  ceph:
    backup:
      backup_dir: /srv/volumes/backup/ceph
