
classes:
- system.linux.system.repo.mcp.extra
- system.linux.system.repo.mcp.apt_mirantis.openstack
- system.linux.system.repo.mcp.apt_mirantis.ubuntu
- system.linux.system.repo.mcp.apt_mirantis.saltstack
- system.linux.system.repo.mcp.apt_mirantis.glusterfs
- system.salt.control.virt
- system.salt.control.cluster.openstack_control_cluster
- system.salt.control.cluster.openstack_proxy_cluster
- system.salt.control.cluster.openstack_database_cluster
- system.salt.control.cluster.openstack_message_queue_cluster
#- system.salt.control.cluster.openstack_upgrade_single
- system.salt.control.sizes.openstack.compact
- system.salt.control.placement.openstack.compact
- system.salt.control.sizes.ovs.compact
- system.salt.control.placement.ovs.compact
#- system.salt.control.cluster.openstack_benchmark_single
- system.salt.control.cluster.stacklight_server_cluster
- system.salt.control.cluster.stacklight_log_cluster
- system.salt.control.cluster.stacklight_telemetry_cluster
- system.salt.control.sizes.stacklight.compact
- system.salt.control.placement.stacklight.compact
- system.salt.control.cluster.cicd_control_cluster
- system.salt.control.sizes.cicd.compact
- system.salt.control.placement.cicd.compact
- system.salt.control.cluster.ceph_mon_cluster
- system.salt.control.cluster.ceph_rgw_cluster
- system.salt.control.sizes.ceph
- cluster.vlab.infra
- cluster.vlab.infra.virtual_osd
- cluster.vlab.infra.virtual_cmp
- cluster.vlab.infra.virtual_k8s
- cluster.vlab.infra.networking.kvm
parameters:
  _param:
    cluster_vip_address: ${_param:infra_kvm_address}
    cluster_node01_address: ${_param:infra_kvm_node01_address}
    cluster_node02_address: ${_param:infra_kvm_node02_address}
    cluster_node03_address: ${_param:infra_kvm_node03_address}
#    deploy_nic: eno1
    primary_first_nic: eno1
    primary_second_nic: eno2
    salt_control_size_cpu_openstack_proxy: 4
    salt_control_size_ram_openstack_proxy: 8192
    salt_control_size_disk_profile_openstack_proxy: small
    salt_control_size_net_profile_openstack_proxy: proxy
    salt_control_size_cpu_openstack_gateway: 4
    salt_control_size_ram_openstack_gateway: 8192
    salt_control_size_disk_profile_openstack_gateway: small
    salt_control_size_net_profile_openstack_gateway: gateway
    salt_control_size_cpu_openstack_message_queue: 4
    salt_control_size_ram_openstack_message_queue: 16384
    salt_control_size_cpu_ceph_mon: 4
    salt_control_size_ram_ceph_mon: 12288
    salt_control_size_cpu_ceph_rgw: 4
    salt_control_size_ram_ceph_rgw: 12288

  salt:
    control:
      cluster:
        internal:
          rng:
            backend: "/dev/random"
          node:
#            bmk01:
#              image: ${_param:salt_control_xenial_image}
            ctl01:
              image: ${_param:salt_control_xenial_image}
            ctl02:
              image: ${_param:salt_control_xenial_image}
            ctl03:
              image: ${_param:salt_control_xenial_image}
            dbs01:
              image: ${_param:salt_control_xenial_image}
            dbs02:
              image: ${_param:salt_control_xenial_image}
            dbs03:
              image: ${_param:salt_control_xenial_image}
            msg01:
              image: ${_param:salt_control_xenial_image}
            msg02:
              image: ${_param:salt_control_xenial_image}
            msg03:
              image: ${_param:salt_control_xenial_image}
            prx01:
              image: ${_param:salt_control_xenial_image}
            prx02:
              image: ${_param:salt_control_xenial_image}
  virt:
    nic:
      default:
        eth1:
          bridge: br-mgm
        eth0:
          bridge: br-ctl
      gateway:
        eth3:
          bridge: br-mgm
        eth2:
          bridge: br-ctl
        eth1:
          bridge: br-mesh
        eth0:
          bridge: br-ext
      cmp:
        eth3:
          bridge: br-mgm
        eth2:
          bridge: br-ctl
        eth1:
          bridge: br-mesh
        eth0:
          bridge: br-ext
      proxy:
        eth2:
          bridge: br-mgm
        eth1:
          bridge: br-ctl
        eth0:
          bridge: br-prx
      osd:
        eth1:
          bridge: br-mgm
        eth0:
          bridge: br-ctl

    disk:
      osd:
      - system:
          size: 51200
      - osd1:
          size: 102400
      - osd2:
          size: 102400
      - osd3:
          size: 102400
      - osd4:
          size: 102400
      - osd5:
          size: 102400
      - osd6:
          size: 102400
      - osd7:
          size: 102400
      cmp:
      - system:
          size: 204800
  #   system:
  #     package:
  #       linux-image-4.8.0-39-generic:
  #         version: latest
  #       linux-headers-4.8.0-39-generic:
  #         version: latest
  #       linux-image-extra-4.8.0-39-generic:
  #         version: latest
  #       linux-headers-4.8.0-39:
  #         version: latest
  #     user:
  #       root:
  #         enabled: true
  #         name: root
  #         home: /root
  #         # Password is cloudlab, comment out, configure your SSH key bellow
  #         # and disable password auth
  #         password: $6$0Qqj.6l.$T9k9Onm9pIDo6ULABVBRNogyizG.9CnwQ4bvI4xH.AWeIGHbLyFU87ejMTtKvAAyd3dncRYbeUV.VbnXJU2u./

