parameters:
  _param:
    # MAAS
    # Do not change below values as needed for prebuilt day01 image
    maas_admin_username: mirantis
    maas_admin_password: r00tme
    maas_db_password: fRqC7NJrBR0x
    # StackLight
    alerta_admin_password_generated: YDCRpln2ET7YVn0P
    grafana_password_generated: QOfnEQDZbTPnEoB1
    mysql_grafana_password_generated: jFAagjycnv4l571T
    influxdb_stacklight_password_generated: NKC82lVUuX5aQv0s
    influxdb_admin_password_generated: 5BvMheqaHDwc08Ks
    influxdb_password_generated: IeQqI4MwPjruXpym
    stacklight_log_keepalived_password_generated: Aqk4NJRe680Wog2Q
    stacklight_telemetry_keepalived_password_generated: yIpgG3oimJWoDJzV
    keepalived_stacklight_monitor_vip_password_generated: fTxYkYtnTHtYgoIX
    keepalived_prometheus_vip_password_generated: eeNhOuLaYnyYqvf5
    stacklight_monitor_rabbitmq_password_generated: G9PNvdQOhoV5zAIG
    stacklight_monitor_uchiwa_password_generated: jhNeCLldW4gS4oUt
    stacklight_monitor_keepalived_password_generated: JtQhYRWNbtEpp80X
    # OpenStack
    horizon_secret_key_generated: J2UIMT8UHq7njD58zx4hEEaj0KddybuEm8fNmwOwadXllzCJRg9cBEofzHDDRBRW
    keystone_swift_password_generated: BfZrmjsygklOz0su
    rabbitmq_openstack_password_generated: GdWX5tp8rv6mgrNF
    heat_domain_admin_password_generated: EGD6SPiXMV1zBbM4
    ceilometer_influxdb_password_generated: cT9MbYhuxkq0n0oK
    billometer_secret_key_generated: QEJ9GRhBFFy4JUNoVPVAd9xqBzxcZmy7QCM3Lbl0krC1ucAAvuQZcqngkJlgVG7p
    mysql_aodh_password_generated: 8pkKaZkvL6VBgymb
    mysql_cinder_password_generated: PQgTkvUnKcPpU3ua
    mysql_ceilometer_password_generated: 4V6NtOzsfFTvaRKe
    mysql_glance_password_generated: AwUbJDrJtfhMpMvW
    mysql_heat_password_generated: CNbFqinOVR3stcTw
    mysql_keystone_password_generated: g5TFUnhaV4Wd0pen
    mysql_neutron_password_generated: RVRuZb0ZnWFOzvSF
    mysql_nova_password_generated: fr7ByqSQuKxwxEjG
    keystone_service_token_generated: HrL52PHIQIGcTAE0
    keystone_admin_password_generated: sKTIt7ZgrLu00a1q
    keystone_ceilometer_password_generated: O88IL4zd9TxmAvSh
    keystone_cinder_password_generated: ZQhBuDCdDxY3IE6w
    keystone_glance_password_generated: Gik02k8krPmWGb1J
    keystone_heat_password_generated: CYHSP9zFH4w5mouc
    keystone_keystone_password_generated: vlHRsJpvaVnXIPVR
    keystone_neutron_password_generated: Uqmh8vymogqjTfMh
    keystone_nova_password_generated: Oe7A2rXJb9rmc9kZ
    keystone_aodh_password_generated: NS72OJBZBaQ8ThYO
    ceilometer_secret_key_generated: AqL0Ont7g8Xt3S8b
    mongodb_ceilometer_password_generated: bTBhvcXmcnQIxcBV
    mongodb_admin_password_generated: 4vbha8HYaqFyPuwD
    mongodb_shared_key_generated: TmxCBCaRK9ShNbsLGhxQzSnQdiwNiqqscvIoWEnQPzzyo0yPY4gHDpFgG16iCSeM
    openstack_metadata_password_generated: ZIrYgrCY0bLedkuQ
    keystone_billometer_password_generated: UZVwDtEJ16K3DnVO
    cinder_storage_secret_uuid_generated: "bf89bb5c-b1c4-9891-cbc2-725bb419e57c"
    nova_storage_secret_uuid_generated: "a5808f5f-bb4e-8925-6e31-c808daa808c8"
    # DriveTrain / CICD
    openldap_admin_password_generated: ItcAcUxnKDwpjXb4
    openldap_config_password_generated: ZGup2HDJEnddK1BQ
    openldap_readonly_password_generated: YRAK5eMHtXUk78I4
    jenkins_admin_password_generated: veFJIhGrGNMzKaqz
    gerrit_admin_password_generated: 2QAgnFw4l1u2QOms
    cicd_keepalived_vip_password_generated: pUa8AXMMLXCdA5nP
    cicd_mysql_admin_password_generated: QioieKo12EtVS01F
    cicd_mysql_gerrit_password_generated: H9FCAktDU8ea4oad
    jenkins_admin_public_key_generated: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDnIhHak1uE5bToHYcslDo4qg0/r/HoUdXyYtggljD7StIjkSISAOVAZdeL10CKvB6DQoOuIH6A1cwNKjA3pesARQzNXv9tumiCb3enjUwcjhBEUJyjMOIAjctek7qznOs+XdQPaU1jlUAhYU9pfMTWlmLcMQzK5mxfpNVePEX43l+rp4DakFwpSrDMFmtEYMSx+uSERvZnpfjZAXCFh/sYU0I8SGRyBPRHDmglYe3LLK3ilQsh7cQVVv8BKtL9MxBDHTHG7v5OJ2MByXzVpwP46Xe1hxFDqBLv93gYF8nIlp+LGSro5R9zGICvtxv1+BVlcD49//qNM+qbgQgqTGDD
    jenkins_admin_private_key_generated: |
      -----BEGIN RSA PRIVATE KEY-----
      MIIEpQIBAAKCAQEA5yIR2pNbhOW06B2HLJQ6OKoNP6/x6FHV8mLYIJYw+0rSI5Ei
      EgDlQGXXi9dAirweg0KDriB+gNXMDSowN6XrAEUMzV7/bbpogm93p41MHI4QRFCc
      ozDiAI3LXpO6s5zrPl3UD2lNY5VAIWFPaXzE1pZi3DEMyuZsX6TVXjxF+N5fq6eA
      2pBcKUqwzBZrRGDEsfrkhEb2Z6X42QFwhYf7GFNCPEhkcgT0Rw5oJWHtyyyt4pUL
      Ie3EFVb/ASrS/TMQQx0xxu7+TidjAcl81acD+Ol3tYcRQ6gS7/d4GBfJyJafixkq
      6OUfcxiAr7cb9fgVZXA+Pf/6jTPqm4EIKkxgwwIDAQABAoIBAQDiVUqGb6Y/DXGJ
      muCzlrMsqdkvdGu+w+Rt5r0dq/VrHmmIyqZCWv4jgZcBKVfagzyd7JRl/wvhvXqD
      qbxtwdvN99ABi/U0zkVo9R6GxKazj6n+O7InW8b0I+XyR1ecax0xhVATh1pxGcYi
      6deJxNQ8Difg12dfiSS2xALstLkQaVVhud48QY6rLXma7/e2j4wOl8JHBJ//fbIm
      3W6lI8/9q2erfPyEV8tUNOMezQLVv1/eBslhuwAZQ5Nn/HgyVshL+jeRNG40EtgU
      d4rq7pJTHH7qGVJA2YeE2MNh8j6A5MnC6WIYamSFoDT+FefTg0TT7NUSNe5DGE8q
      6SzTbU+BAoGBAPilyUiLFbDKifcoM5t27MoHJUi69r6DngD86WYRvitqnrZerv+L
      RBi4Xq1QyIxXlw9RravJ9LxN+i7zYpRflfhLHnV91dPmJsEPT7VNhiQpnLFjWcLD
      2+D/kubpwdNfAYc0Y4JTVNxtKb7IpqYqJFQ1ciOhPUYhKqLsrI0nPFMvAoGBAO33
      s7aH5p3qizieCi5M8gWnDbTwJ6lrB3N4NdMrh3ol11+LPz32kIs34mCRZDVWeL+S
      2xatapEcrmTIV3dL7CE2V2/4P6d34/2iP/T3BHu57GRCooDAmKfD+Em3+5XVXms3
      S6BHpdjBXcUJbBao/6Hy15T3uvrpfS0efVRIt/atAoGAWO16Or67qDoX89Rl+LEk
      6PB7TjLH8sVB6lqJ4x5vZDnCv7jHX8/gL/MosVXWFBNzjGAK/AjDxeEhnE8hr60s
      Btxe7Whu5FVJAP1H5bDvS9myF+NPhA/mgOcHFB0AXGd7NW7wM/k3vYoxRvGeYIlr
      6s4en02Yi49rH1AEOouQ0LMCgYEAl2VzGZrmtutEfdXWRlS/2abJiqcLpLaqO+Vr
      4RidjbHLj0bJCoP2vAvm42c8qM6F7ePhrVDRLtdfgFERjJ1p8ktfX6ZB4SreizwR
      kqkhWhIUekkGmAFwXbPJICWEU3Q3KOE6JRPQSNHk9XmkIdqNIJyeWXEurXmlIPJ3
      7AqDt9UCgYEA4LedEk27H4KpX82ptS+bfw7+dVmTgw4GbJ+Iy32brQ9oUdHRBXYg
      +5ic5Rs280ksTYjSEDaoN9ZHb+oVWPxir2wMDZj8ty0nfIZRXnlKWd60lulyTQLJ
      kKJFF1YQYmnmKyAEN5QPli5zT7H9LCPwv4kCBo66jnuFDM4eOy2rQn0=
      -----END RSA PRIVATE KEY-----
    # Ceph
    rgw_keepalived_vip_password_generated: y94euOwexqX
    ceph_cluster_fsid_generated: "7c45926b-19ac-6820-9394-d818467fc972"
    rabbitmq_admin_password_generated: uKuEUUy92KZ2FtHc
    rabbitmq_secret_key_generated: 01akZdUV1mxkZXxy
    galera_server_maintenance_password_generated: RvSo7o16TusZKgMk
    galera_server_admin_password_generated: 8jORfSjdJ5q1Oqw8
    docker_registry_http_secret_generated: 68cgIINOppU5XOGV
