parameters:
  _param:
    # MAAS
    # Do not change below values as needed for prebuilt day01 image
    maas_admin_username: mirantis
    maas_admin_password: r00tme
    maas_db_password: fRqC7NJrBR0x
    # StackLight
    grafana_password_generated: VJpBOe3WAblgBwR2
    mysql_grafana_password_generated: 7Bt8pSmoPiO6oel1
    influxdb_stacklight_password_generated: i3JgUBCwJKVde4DL
    influxdb_admin_password_generated: 8MYrVgfWYVKDOdbP
    influxdb_password_generated: 9RGaL5ZesyWIJgCL
    stacklight_log_keepalived_password_generated: 7HzxZMfPfoGXoung
    stacklight_telemetry_keepalived_password_generated: BJEID6WROjQImcjb
    keepalived_stacklight_monitor_vip_password_generated: KPEnP7yiFrrimbSc
    keepalived_prometheus_vip_password_generated: FDmkWVv3U3Lzq9w5
    stacklight_monitor_rabbitmq_password_generated: EfXfnHFrZjMKJCx4
    stacklight_monitor_uchiwa_password_generated: zDbjSrhRHWJUdoPC
    stacklight_monitor_keepalived_password_generated: JxSUUXRt7oDyijVq
    # OSS
    oss_postgresql_admin_user_password_generated: MHGC20jcgszX7q8E
    pushkin_db_user_password_generated: z87xbgpTvtUpVQZ1
    secmonkey_db_user_password_generated: PEzXBRnPNu9us3tV
    docker_mongodb_admin_password_generated: haKWZUSDkRncQyj9
    rundeck_db_user_password_generated: uIzclYly4eyAwsOV
    oss_openstack_cert_generated: |
            -----BEGIN CERTIFICATE----- MIIE0DCCA7igAwIBAgIBBzANBgkqhkiG9w0BAQsFADCBgzELMAkGA1UEBhMCVVMx EDAOBgNVBAgTB0FyaXpvbmExEzARBgNVBAcTClNjb3R0c2RhbGUxGjAYBgNVBAoT AAGjggEaMIIBFjAPBgNVHRMBAf8EBTADAQH/MA4GA1UdDwEB/wQEAwIBBjAdBgNV 91cxG7685C/b+LrTW+C05+Z5Yg4MotdqY3MxtfWoSKQ7CC2iXZDXtHwlTxFWMMS2 -----END CERTIFICATE----- -----BEGIN CERTIFICATE----- dGhvcml0eSAtIEcyMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAv3Fi 9kIDN0zmiN/VryTyscPfzLXs4Jlet0lUIDyUGAzHHFIYSaRt4bNYC8...
    rundeck_runbook_public_key_generated: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC9KPJNaUHthGAbBQN9ZxVAMB6p9ba4jYahk2AKuWbs7Wl5tAXzAwgVEcxmYKJ9rBaWIGjjFl/jfLjnahKO1JNmp8fxyGJO8dU5Xsbl2V1ms8lXjO/vjObdxMgkSclLFp6Napzd2Tnk3lTs5JttwbmJe8M7+yaKEVJcboyNW9GIB8rYKwdoq1Vd2U27QnNVwN+pS8EyGcBzlYr8f1mfRRe5kI+QzUgnnpp13tz3xNpomDCkFzLt583V1CLmM0DCt4+zcbPgDG3ECdPtC5nsQUvFei2cw7E5cTfcP3iUeqRlIwS5MIAmqXscYXQnkBtPJ1BKQEQPs8UyE9MhJ9kjFmlh
    rundeck_runbook_private_key_generated: |
      -----BEGIN RSA PRIVATE KEY-----
      MIIEowIBAAKCAQEAvSjyTWlB7YRgGwUDfWcVQDAeqfW2uI2GoZNgCrlm7O1pebQF
      8wMIFRHMZmCifawWliBo4xZf43y452oSjtSTZqfH8chiTvHVOV7G5dldZrPJV4zv
      74zm3cTIJEnJSxaejWqc3dk55N5U7OSbbcG5iXvDO/smihFSXG6MjVvRiAfK2CsH
      aKtVXdlNu0JzVcDfqUvBMhnAc5WK/H9Zn0UXuZCPkM1IJ56add7c98TaaJgwpBcy
      7efN1dQi5jNAwrePs3Gz4AxtxAnT7QuZ7EFLxXotnMOxOXE33D94lHqkZSMEuTCA
      Jql7HGF0J5AbTydQSkBED7PFMhPTISfZIxZpYQIDAQABAoIBADU3veO1h0zRf1Ba
      ur6fL8VdRGNAs+V8O7Jdihm6S5DAwnnxAfN6mN2EomLzMQP2VGxsNdYdx2BzCHpi
      x1HT0JyC+6e0XqQjOX/ogEDORI7Oagjtp9tXYuRlpoE/GRi9BmJ26icoJDeVrYLw
      ViIs7IwXe7f2UsNpWCiVGYnzmSGRwxENOhMdRxC7j+0/bXgkVqnbZmCJ6L+s3htt
      z6SyW2C0Jx9aK5hSyHnUecn4Om+noCbRv6eSTRFUlHByXHIFLCoRC8S9FSmcS8nG
      sIXgFBIo7W13UpoY5KGQURl3y2fUV4nPLivlS110LMCb08ujEIe57QxG4L0ooWxm
      FhUghIECgYEA9hVhQz8mrLVO+jdu+SxdwpB5Apnj3SoW24ZH9GaG6htGG+vn1fy4
      OWeY3C7Ytmc4jZC12GMu98C2Y2cTVDgrIMi3/jTVGFTPuMC2CMUn5SOS6kXf/4M9
      Jjw2s76Vl8QxF2S1tXsJw7AnvrFJR/pEt8tmwBXgfxRLIRONqyJaYskCgYEAxMhW
      e4rNE8MiUrnmmZL3cW2LdXr3TpddHbMWK0n8vXkyxHVBQ5exTU29VKPoDZHhmO8W
      gqY9z9byZ3uysniy1boyVt6MeVuL5Le6B7enqTDXzTSq/U5pLipA/crNdie10QgT
      78Em7siB4H4gjfkDo16v6D74cS9l6f4rbmjUxdkCgYBN5CaNKogLUrhU6wbtR+XF
      mAU1lZBSiOgDRFWyPmGl6EwgumL/kKafRPNVfl6KHdIAvTVR8NMFCLKydAXiOoUs
      M1xJ0l9A/Fdjm1wDGqSuGrx9+vAT6G6Kk7Sc4E5pY2hGh1Icx30nu7JY4bTYW5c0
      teUoF8SfdMTzC0VkTdNeQQKBgFoitdJi8qrBsAAanPDta6AuIDoQuCTsmj9XX6k2
      e6lCUanBV8KhQhp5qGaTqWBF2QMXSMVRZnDEMUaLV3/+X1QctKAr0kZoU3zRV0nf
      qtGJyN9653OdrfnyatCVS2V6rQJxY8hnPfEUMMFmpHzDehIj9gk4hs45esIipTwu
      kn+JAoGBAO7c5VG2yh+nHR//sTrR03q34T+ajuKteadDu8QQU893fkGsc9rIraep
      m4WPbpll0acAS+3vabto1f6OvGVsHCsiWL+Kp3lz2qvPPisMF3tXFkeNlXtKdu3X
      N6PH02jr2HNOSf9TppTRHWU0ecrPWkDcEh+rU61b50y9ySqMNnNK
      -----END RSA PRIVATE KEY-----
    # OpenStack
    horizon_secret_key_generated: Y0Bv6Oi6tQMpIQ2Kgrar5W9HbzRfboUIKqPylyggc2vh3y9FvylOyoaANUllFT3Z
    keystone_swift_password_generated: Awr8V5A7b5BiSSC2
    rabbitmq_openstack_password_generated: QSKive2U1LGfkObQ
    heat_domain_admin_password_generated: BZHPMdE6kR0rXGZD
    ceilometer_influxdb_password_generated: r4AwaC9tXKdpWGqD
    billometer_secret_key_generated: 8zTaAWRAzIq5MvQ8n4KCgFzNlwaqZhfLabkimv7PNpw7Ciz7Q9tIulcjiaYzwylD
    mysql_aodh_password_generated: 320nOyyJgH56OMZ9
    mysql_cinder_password_generated: vpFazC0Cfk3SBbir
    mysql_ceilometer_password_generated: wp8vSnl19YoQkJ5K
    mysql_glance_password_generated: QdZwpVuRVlLhepb5
    mysql_heat_password_generated: rw2RPagLwKN7emkD
    mysql_keystone_password_generated: Auw2hLw7obRSSVzL
    mysql_neutron_password_generated: RS0eRCrheQjn4RfY
    mysql_nova_password_generated: fLmZvZkIROQqVTgv
    keystone_service_token_generated: 0lGj128wLW7f5X6h
    keystone_admin_password_generated: FU8TgwStmqJopMpO
    keystone_ceilometer_password_generated: DPYA0qSCMDW0Y1pr
    keystone_cinder_password_generated: MjsNFDdVitkc6oPE
    keystone_glance_password_generated: TJ7mttZuUJ78oO01
    keystone_heat_password_generated: fWeJeWVXdcpjyPaS
    keystone_keystone_password_generated: 9Ca4co3IGa38hGnP
    keystone_neutron_password_generated: p26uMKcu8xlPueOg
    keystone_nova_password_generated: lrI874RtkMnRGHRk
    keystone_aodh_password_generated: zxxPXcSZloT8Xbpl
    ceilometer_secret_key_generated: qnp79vfyoF2Fm15L
    mongodb_ceilometer_password_generated: y830duUia6kJ13Au
    mongodb_admin_password_generated: EXrt1sUByYilb9Zf
    mongodb_shared_key_generated: jFd5C2gM3jIrtQMkFqliWLG6dYqVUVjm4khujtsM6okN1ThrqZLOeofz2fPriuCb
    openstack_metadata_password_generated: yShjbdmjxjtOabyK
    keystone_billometer_password_generated: 3v6Kqm1sRnqaegcV
    cinder_storage_secret_uuid_generated: "9724eec7-8eaa-3a16-20fc-16cd970259c1"
    nova_storage_secret_uuid_generated: "60e09ef8-f85b-1645-9f60-d21fcd64d56b"
    # DriveTrain / CICD
    openldap_admin_password_generated: lT6mlP2j74u5oOIV
    openldap_config_password_generated: d7w6J279XmjJkfRv
    openldap_readonly_password_generated: DwNGOb6PuWycys96
    jenkins_admin_password_generated: TvTWbonTCJIVkmXf
    gerrit_admin_password_generated: zGa6HIOP0swZNv04
    cicd_keepalived_vip_password_generated: q41nOJmzOOeYgYmI
    cicd_mysql_admin_password_generated: iIY8E0YRSVSXCOeP
    cicd_mysql_gerrit_password_generated: ELHzfCuTA2VkdiQI
    jenkins_admin_public_key_generated: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC3DX4AtCFXW7JIazKoDJe6p0MxeIqB3mKcaUZvQ+GrZun6wdQcMGzkXKlT6yO70YYbrEIhELdEsc7Fl6ouT7DT/EGFgR0xRcy+W3XykdBNW1DHSt1iszBP8xIaGusCOUvOxPl5CI7xGk1xAEAdCvhMjxOP9rzPtGsAhCD+8NAJ/xuHX1gfbaQ9fijEdlrnJhjY9SeC1IAJqBd3koxngS4GSxESRqmn/dR5SkHY8HnnYNvBwfcQumPJOS6Tz4kUVzjVeBQNpkuQdjftv8MAZaavWGzKAv2CP3IAEcB5nvgVhz4meaMOsxDPsHEs3WAnyoE8Zm57ja+MOdN4e49NsZqP
    jenkins_admin_private_key_generated: |
      -----BEGIN RSA PRIVATE KEY-----
      MIIEpAIBAAKCAQEAtw1+ALQhV1uySGsyqAyXuqdDMXiKgd5inGlGb0Phq2bp+sHU
      HDBs5FypU+sju9GGG6xCIRC3RLHOxZeqLk+w0/xBhYEdMUXMvlt18pHQTVtQx0rd
      YrMwT/MSGhrrAjlLzsT5eQiO8RpNcQBAHQr4TI8Tj/a8z7RrAIQg/vDQCf8bh19Y
      H22kPX4oxHZa5yYY2PUngtSACagXd5KMZ4EuBksREkapp/3UeUpB2PB552DbwcH3
      ELpjyTkuk8+JFFc41XgUDaZLkHY37b/DAGWmr1hsygL9gj9yABHAeZ74FYc+Jnmj
      DrMQz7BxLN1gJ8qBPGZue42vjDnTeHuPTbGajwIDAQABAoIBAQCRIWldNXOZx2G6
      eQNYqWNC4Yoslt15yc91IyJs5Ozu8FFiNnrtPpeXFsBJgIx8RMqG9jQX8yDanf7K
      Okz7GsOfzshECPIUNrr10Z3aDDGSo2uQFpMfxeHwAU/A0sawpKyt6w3AIED0d14e
      0YwDescSK/3ejkl0hB6x8hAXEOZghUGI9dX/45BwWKFHau2sP1BD/9AqTehTn7vL
      fPeTS6GcHBb0GIaTP78WPOzE5jHDxjTfW8EsOCDmMNUdTE6PxitNi7RYbsWzHV3G
      scPd0Gn8i2UM88XoY6F4TiYMx+TbNpUpVO+S2r2A73Y/pJz6h/Bq/pAf7E0rkH05
      QMHDyM+BAoGBAO329xwRL3H0FZRdixRJOUtScUFHQoS30lYXzhtQfXdixxXtd16H
      5/hE/oLS/PQpUhE1V8A5Ql2bb4yQ+LwVgeikYOtLcCN6PLo00ftB0Xfq5SxH5REY
      DrKfWOt/wekwpBxIYUQn8Dz01NAg79Gp7rOnWX8nTbaw4cQiFm9cVbTZAoGBAMTt
      HTusNda++l4WiAEDoWE8flxZTHDY8vb2aFBfzE+wLdgkdSNqeDp0j9ci3gIqaNnk
      lUCyDsLTt0njdTC8CoIct8QIeRekOLLLVn4819vuoxgHBR4OnzftwCG97GwEKm6b
      3iZ/6oRCD6krpJOowdp+8Zrez51L7LCTTREZtQmnAoGAFtijGNq9h187wybH94ag
      LY8YuH+y7zMGyqU2cIDlytR88Kn/z9+Ucc2N8dl316kv698HMblNmdcWepRgjQ4z
      jrZZZ72yYnWV5vqzPkAvcCfpILs2TtHUd2m9C78USuMUnnKEhBqhgfivhdvjqml6
      NV1XxlFrsKKCymXLaZ2fzOECgYEAugJ/Km5wLHgYZedCcDLNrNtHQFPZMH68gSof
      Pkw+4Ma5hwBo5RsclZqkg8IbklAc2jRgBswpxT3WU6TWfUIhauVVb4XRW9Ny+u+2
      s2clPkkbJQb8fnexTVL1uOl8+Eq3CeOQ4yzQiD0eLd1bh15QPeLKtE7iLOIaoG+C
      zDRMHOECgYAWEiSAdZCQq0bDe+8Ze+R8OI6orhg9ZkYas81Umrh2G8XU1Qo3irFR
      u8SjqWt0Oc5AImMdiUWPoqnpZa7ozYGrPZsAijRb0DCUDTtgW/P9woXwVTwxBOvQ
      rqJl3wlIufXjRraLlx7Vlhh44FQXUmx05xquY98clv3n2tRns6XjPA==
      -----END RSA PRIVATE KEY-----
    # Ceph
    rgw_keepalived_vip_password_generated: 0DYiC16DWxr
    ceph_cluster_fsid_generated: "e19214d3-d994-d9f9-aa31-5de913d3f82f"
    rabbitmq_admin_password_generated: akfLhACixiIjS8Th
    rabbitmq_secret_key_generated: 5JzuATdRbIWbF27w
    galera_server_maintenance_password_generated: 9OzcDIqcTeegDiEq
    galera_server_admin_password_generated: WKSLju1bk9YeAkkX
    docker_registry_http_secret_generated: a6bUyOS23bpK9qA6
