parameters:
  salt:
    control:
      size:
        ceph.osd:
          cpu: 4
          ram: 16384
          disk_profile: large
          net_profile: osd
      cluster:
        internal:
          domain: ${_param:cluster_domain}
          engine: virt
          node:
            osd001:
              name: ${_param:ceph_osd_rack01_hostname}001
              provider: ${_param:infra_kvm_node01_hostname}.${_param:cluster_domain}
              image: ${_param:salt_control_xenial_image}
              size: ceph.osd
              rng:
                backend: /dev/urandom
            osd002:
              name: ${_param:ceph_osd_rack01_hostname}002
              provider: ${_param:infra_kvm_node02_hostname}.${_param:cluster_domain}
              image: ${_param:salt_control_xenial_image}
              size: ceph.osd
              rng:
                backend: /dev/urandom
            osd003:
              name: ${_param:ceph_osd_rack01_hostname}003
              provider: ${_param:infra_kvm_node03_hostname}.${_param:cluster_domain}
              image: ${_param:salt_control_xenial_image}
              size: ceph.osd
              rng:
                backend: /dev/urandom

